export const choicesMap = {
  Yes: "Yes",
  No: "No",

  Facility: "Facility",
  Non_Facility: "Non-Facility",

  Grants: "Grants",
  Cash_Donations: "Cash Donations",
  Membership_Dues: "Membership Dues",
  Foundation: "Foundation",
  Fundraising: "Fundraising",
  Crowd_Funding: "Crowd Funding",
  Corporate_Partnerships: "Corporate Partnerships",
  Corporate_Social_Responsibility_CSR: "Corporate Social Responsibility (CSR)",
  International_Organisations: "International Organisations",
  Government_Fundings: "Government Fundings",
  Contributions: "Contributions",
  Individual_Donors_Philanthropy: "Individual Donors Philanthropy",
  Investment_Income: "Investment Income",
  Loan: "Loan",
  Zakaat_Sadaqah: "Zakaat/Sadaqah",
  Offering: "Offering",
  Waqf: "Waqf",
  Endowment: "Endowment",
  Out_of_Pocket_or_Patient_Payment: "Out of Pocket/Patient Payment",
  Other_funding_sources: "Others",

  HIV_Prevention: "HIV Prevention",
  HIV_Testing: "HIV Testing",
  HIV_Counseling: "HIV Counseling",
  Referral: "Referral",
  Treatment: "Treatment",
  Viral_Load: "Viral Load",
  PMTCT: "PMTCT",
  Early_Infant_Diagnosis_EID: "Early Infant Diagnosis (EID)",
  Laboratory_Services: "Laboratory Services",
  TB_Screening_and_Treatment: "TB Screening and Treatment",
  Psycho_Social_Support: "Psycho-Social Support",
  Other_services: "Other Services",

  Community_Outreaches: "Community Outreaches",
  Advocacy: "Advocacy",
  FLHE: "FLHE",
  OVC_Support: "OVC Support",
  Care_and_Support: "Care and Support",
  Operation_Triple_Zero: "Operation Triple Zero",
  Adherence_Counseling_and_Support: "Adherence Counseling and Support",
  Gender_and_Human_Rights: "Gender and Human Rights",
  Counseling: "Counseling",
  Social_Protection: "Social Protection",
  Contact_Tracing: "Contact Tracing",
  Mentoring: "Mentoring",
  Coordination: "Coordination",
  Other_non_facility_services: "Other Services",

  Antenatal_Clinic: "Antenatal Clinic",
  Pharmacy: "Pharmacy",
  Laboratory: "Laboratory",
  Maternity_Ward: "Maternity Ward",
  ART_Clinic: "ART Clinic",
  Other_service_delivery_point: "Other Service Delivery Points",

  TB_Services: "TB Services",
  Malaria: "Malaria",
  Syphilis: "Syphilis",
  Other_services_rendered: "Others",

  Community: "Community",
  Church: "Church",
  Mosque: "Mosque",
  Faith_Homes_Prayer_Houses: "Faith Homes/Prayer Houses",
  Orphanages: "Orphanages",
  Maternity_Homes: "Maternity Homes",
  Educational_Institution: "Educational Institution",
  Other_service_delivery_point_non_facility: "Other Service Delivery Points",

  Doctors: "Doctors",
  Nurses_Midwives: "Nurses Midwives",
  Pharmacists: "Pharmacists",
  Community_Health_Extension_Workers_CHEW:
    "Community Health Extension Workers (CHEW)",
  Junior_Community_Health_Extension_Worker_JCHEW:
    "Junior Community Health Extension Worker (JCHEW)",
  Lab_Scientist: "Lab Scientist",
  Lab_Technicians: "Lab Technicians",
  Pharmacy_Technicians: "Pharmacy Technicians",
  Physiotherapist: "Physiotherapist",
  Biomedical_Engineers: "Biomedical Engineers",
  Dentist: "Dentist",
  Opticians: "Opticians",
  Social_Workers: "Social Workers",
  Data_Clerk: "Data Clerk",
  Community_Health_Officers: "Community Health Officers",
  Radiographers: "Radiographers",
  Monitoring_and_Evaluation_Officers: "M&E Officers",
  Religious_Leaders: "Religious Leaders",
  Security_Officers: "Security Officers",
  Volunteers: "Volunteers",
  Other_human_resources_for_health: "Others",

  PMTCT_Register: "PMTCT Register",
  ANC_Register: "ANC Register",
  HTS_Register: "HTS Register",
  OVC_Register: "OVC Register",
  HIV_Register: "HIV Register",
  ART_Register: "ART Register",
  ART_Monthly_Summary_Form: "ART Monthly Summary Form",
  Adult_Initial_Clinical_Evaluation_Form:
    "Adult Initial Clinical Evaluation Form",
  Peadiatric_Initial_Clinical_Evaluation_Form:
    "Peadiatric Initial Clinical Evaluation Form",
  Laboratory_Order_and_Results_Form: "Laboratory Order and Results Form",
  Viral_Load_Order_and_Results_Form: "Viral Load Order and Results Form",
  Pharmacy_Order_Form: "Pharmacy Order Form",
  Pharmacy_Daily_Worksheet: "Pharmacy Daily Worksheet",
  TB_Preventive_Therapy_Cohort_Register:
    "TB Preventive Therapy Cohort Register",
  Viral_Load_Monitoring_Register: "Viral Load Monitoring Register",
  EAC_Form: "EAC Form",
  EAC_Monitoring: "EAC Monitoring",
  HIV_Patient_Tracking_Register: "HIV Patient Tracking Register",
  Intensive_Follow_up_Form: "Intensive Follow-up Form",
  PEP_Register: "PEP Register",
  Facility_DSD_Register: "Facility DSD Register",
  Community_DSD_Monitoring_Register: "Community DSD Monitoring Register",
  PrEP_Card: "PrEP Card",
  PrEP_Register: "PrEP Register",
  PrEP_MSF: "PrEP MSF",
  Client_Intake_Form: "Client Intake Form",
  Request_and_Result_Form: "Request and Result Form",
  Daily_HIV_Syphilis_Testing_Worksheet: "Daily HIV Syphilis Testing Worksheet",
  HIV_Testing_Register: "HIV Testing Register",
  Client_Referal_Form: "Client Referal Form",
  HIVST_Register: "HIVST Register",
  HTS_Monthly_Summary_Form: "HTS Monthly Summary Form",
  Other_documentation_tools: "Other Documentation Tools",

  Activity_or_Annual_Reports: "Activity or Annual Reports",
  Other_documentation_tools_non_facility: "Other Documentation Tools",

  SACA: "SACA",
  SASCP: "SASCP",
  Donor: "Donor",
  Implementing_Partners: "Implementing Partners (IPs)",
  Domestic_Funders: "Domestic Funders",
  LACA: "LACA",
  NiFCOB_AIDS: "NiFCOB-AIDS",
  Others_reporting_line: "Others",
};
